<?php

$this->title = ':(';
$this->headTitle()->append($this->title);

$this->import_Css(array('out/esterno'));

?>
<div style="text-align: center;">
    <?= $this->import_Img("out/iscrizione.png", array('alt' => 'Iscrizione')) ?>
    <br />
    <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'default'), 'default') ?>">&lt;-- Torna alla homepage</a>
    <br /><br />
    Qualcosa è andata male durante la fase di registrazione. Sei pregato di rieseguire la procedura, facendo magari più attenzione al significato dei diversi campi.
    <br /><br />
    <a href="<?= $this->url(array('controller' => 'index', 'action' => 'register', 'module' => 'default'), 'default') ?>">&lt;-- Torna alla registrazione</a>
</div>