<?php

$this->title = ':)';
$this->headTitle()->append($this->title);

$this->import_Css(array('out/esterno'));

?>
<div style="text-align: center;">
    <?= $this->import_Img("out/iscrizione.png", array('alt' => 'Iscrizione')) ?>
    <br />
    <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'default'), 'default') ?>">&lt;-- Torna alla homepage</a>
    <br /><br />
    La registrazione è avvenuta con successo. Ora per completare la procedura devi accedere alla tua email e cliccare sul link di conferma che ti è stato inviato.
    <br /><br />
    Buon divertimento!
</div>