<?php

$this->import_Css();
$this->import_Js();

?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?= $this->headTitle() . "\n" ?>
    <?= str_replace("\n", "\n    ", $this->headMeta()) . "\n" ?>
    <?= str_replace("\n", "\n    ", $this->headLink()) . "\n" ?>
    <?= str_replace("\n", "\n    ", $this->headStyle()) . "\n" ?>
    <?= str_replace("\n", "\n    ", $this->headScript()) . "\n" ?>
</head>

<body class="body_esterno">
    <div class="contenitore">
        <?= $this->layout()->content ?>
    </div>
</body>

</html>